// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRcWqS0yVCkZ39f195_kDTGop_tVLOHk',
    appId: '1:778949766254:web:d8633307afbdd5d4cdca7f',
    messagingSenderId: '778949766254',
    projectId: 'crudapp-76145',
    authDomain: 'crudapp-76145.firebaseapp.com',
    storageBucket: 'crudapp-76145.appspot.com',
    measurementId: 'G-FBJGPR8CQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmTC_PqoqC7gcDF29UNSxxWYDSGtSks8M',
    appId: '1:778949766254:android:19ac4a54052b8d01cdca7f',
    messagingSenderId: '778949766254',
    projectId: 'crudapp-76145',
    storageBucket: 'crudapp-76145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5SJF8DjXFVJdizlj__JKKL0xSHmUk_vw',
    appId: '1:778949766254:ios:0b08a1ba1220b350cdca7f',
    messagingSenderId: '778949766254',
    projectId: 'crudapp-76145',
    storageBucket: 'crudapp-76145.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5SJF8DjXFVJdizlj__JKKL0xSHmUk_vw',
    appId: '1:778949766254:ios:7ebf460f26aa9601cdca7f',
    messagingSenderId: '778949766254',
    projectId: 'crudapp-76145',
    storageBucket: 'crudapp-76145.appspot.com',
    iosBundleId: 'com.example.crudApp.RunnerTests',
  );
}
